colors:
    0: CARREAUX
    1: COEUR
    2: PIQUE
    3: TREFLE
values:
    0: 2
    1: 3
    2: 4
    4: 5
    5: 6
    6: 7
    7: 8
    8: 9
    9: 10
    10: VALLET
    11: DAME
    12: ROI
    13: AS